### ISSUE TITLE
Support URLs that don't start with `/static/`

### ISSUE THREAD

**Issue by nureineide** [eudicots/Cactus#177]
In [`template_tags.py#L19`](https://github.com/koenbok/Cactus/blob/master/cactus/template_tags.py#L19) a `TODO` says exactly that.

I'd like to tackle this one, as we need it in one of our projects. 

Do you have any hints on how to do this? Introduce a config setting, and if present use that as a base url for static assets? Did you have any concrete plans/ideas on how to implement this?

I wonder if it would be a good idea to reuse django's [`STATIC_ROOT` related capabilities](https://docs.djangoproject.com/en/1.5/ref/settings/#static-root) (or rather the [`collectstatic` contrib](https://docs.djangoproject.com/en/1.5/howto/static-files/) to be exact) for that. 

But this would somehow contradict the item on the roadmap (see #117) which states/asks, that other template engines than Django's would be a nice feature.

**Comment by nureineide** [comment]
I wonder if it would be a good idea to reuse django's [`STATIC_ROOT` related capabilities](https://docs.djangoproject.com/en/1.5/ref/settings/#static-root) (or rather the [`collectstatic` contrib](https://docs.djangoproject.com/en/1.5/howto/static-files/) to be exact) for that. 

But this would somehow contradict the item on the roadmap (see #117) which states/asks, that other template engines than Django's would be a nice feature.

**Comment by nureineide** [comment]
Hi @krallin,

Do you have an opinion on what approach you'd prefer? Should I hack the template tag or implement it as a new tag/plugin? Or should I just make a concrete implementation which you then can review? 

Of course I could just hack something for our use case, but I imagine a solution for this could be useful for more people and I'd like to contribute it back to cactus and want to ensure I at last start working in the "right" direction.

Thanks a lot for your time & consideration!

Cheers!

**Comment by krallin** [comment]
Hey @nureineide,

I'm sorry, I haven't really had time to look at this (but I'll try and do so this weekend). I wish I could give you a quick and straightforward answer but the truth is I don't really recall whether I knew how to address the problem when I wrote  the TODO.

Generally speaking regarding editing existing functionality vs. building something new:

+ Building something new or a plugin if you cannot preserve backwards compatibility otherwise.
+ Building something new or a plugin is good if you want to make a feature optional (e.g. #141 which I desperately need to review).
+ For all other cases, editing existing functionality is fine.

Hope this helps! I'll try and follow up as I can.

Cheers,

**Comment by nureineide** [comment]
Yes, this helps & is enough for now. I can take a stab from here and publish what I did. You then can decide if you'd like to integrate it at some point.

**Comment by abhay1** [comment]
I found a hacky way to do this. Simply include a `static-url` in the `config.json` and append this value while returning in the `get_url_for_static` function. Same can be extended for `root-url` if the pages aren't hosted in TLD.

**Comment by eMerzh** [comment]
is there any news on this ? because it's really a blocker for running it in gitlab or other sites like this

**Comment by nureineide** [comment]
We went the route of implementing a simple plugin, that reads an optional `config.json` file and given that file contains a key named `static_base_url` sets the template variable `STATIC_URL` to the respective value.  
This also allowed us to maintain most of our cactus v2 templates unchanged.

The following is the plugin code, which you are free to use as is.
```python
import os
from cactus import config

INFO = {
    'name': 'CUSTOM_STATIC_URL',
    'description': 'Set STATIC_URL to value from config.json in project dir'
}

STATIC_URL_KEY = 'static_base_url'
conf = config.Config('config.json')

def preBuildPage(site, path, context, data):
    if conf.get(STATIC_URL_KEY):
        context.update({ 'STATIC_URL': conf.get(STATIC_URL_KEY) })
    else:
        context.update({ 'STATIC_URL': '/static' })
    return context, data
```

... and a sample `config.json`
```json
{
    "static_base_url": "https://cdn.example.com/somepath"
}
```

I'll close this issue, as I'll not put any further work into it. Sorry, for keeping it open for so long, without any update.

**Comment by thiagof** [comment]
The plugin does not work with the `static` tamplate tag
