### ISSUE TITLE
Page.path of blog wrong for prettified urls

### ISSUE THREAD

**Issue by blattms** [eudicots/Cactus#233]
When setting prettify_urls to True, Page.path is not the URL that the page is uploaded to but the one where the source of the page is (including the .html extension).

**Comment by matthewjewell** [comment]
Yes, came here to report this - I see PR #229 which solves it...hopefully will be merged soon. Presumably a quick hack to blog.py would also do the trick (context_post), but not a big enough issue for me to check that out at the moment.

**Comment by blattms** [comment]
Closing as PR #229 was merged
