### ISSUE TITLE
locale problem in django 1.6.11

### ISSUE THREAD

**Issue by andpozo** [eudicots/Cactus#263]
I was define my config.json as:

```json
{
  "locale": "es"
}
```
when I execute from command line:
```bash
$ cactus messages:make
```

the result is locale with two folders inside:

```bash
e/    s/
```

NOTE: if the language code is 'en'... the folders would are "e/    n/"

**Comment by m-thielen** [comment]
This is due to a bug in cactus. A simple workaround is:

    django-admin.py makemessages -l es

This will update/create the po file for you.

**Comment by m-thielen** [comment]
I provided a fix and created a pull request for this bug:
https://github.com/eudicots/Cactus/pull/267
